name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: sudo apt-get install -y nasm xorriso grub-pc-bin grub-common gcc-cross-x86_64-elf
    - name: clean
      run: make clean
    - name: make
      run: make
