name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: sudo apt-get install -y docker && sudo docker build buildenv -t hexa && sudo docker run --rm -it -v $PWD:/root/env hexa
    - name: Clean
      run: sudo docker run --rm -it -v /home/ks/cHEXAos:/root/env hexa make clean
    - name: Build
      run: sudo docker run --rm -it -v /home/ks/cHEXAos:/root/env hexa make
